# Generated by Django 4.2.2 on 2023-07-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_saleprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_banner_product',
            field=models.BooleanField(default=False),
        ),
    ]
